// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRH5wBA5yoUIsn-Bfby1dmZWMLZkbsF-k',
    appId: '1:474637384308:web:0a607ef857b2306375af21',
    messagingSenderId: '474637384308',
    projectId: 'skillshare-6a544',
    authDomain: 'skillshare-6a544.firebaseapp.com',
    storageBucket: 'skillshare-6a544.firebasestorage.app',
    measurementId: 'G-TQSRW0DNKC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSWSX-OkzWMVTNznYCA7FcTzun85e0ods',
    appId: '1:474637384308:android:e7a731982e1abae475af21',
    messagingSenderId: '474637384308',
    projectId: 'skillshare-6a544',
    storageBucket: 'skillshare-6a544.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIs2LKBnESmjjwFRSKpYu_OHJdtJL8hWk',
    appId: '1:474637384308:ios:8aa4b98cf891ff4f75af21',
    messagingSenderId: '474637384308',
    projectId: 'skillshare-6a544',
    storageBucket: 'skillshare-6a544.firebasestorage.app',
    iosBundleId: 'com.example.skill',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIs2LKBnESmjjwFRSKpYu_OHJdtJL8hWk',
    appId: '1:474637384308:ios:8aa4b98cf891ff4f75af21',
    messagingSenderId: '474637384308',
    projectId: 'skillshare-6a544',
    storageBucket: 'skillshare-6a544.firebasestorage.app',
    iosBundleId: 'com.example.skill',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRH5wBA5yoUIsn-Bfby1dmZWMLZkbsF-k',
    appId: '1:474637384308:web:ea0dfdbd621d070375af21',
    messagingSenderId: '474637384308',
    projectId: 'skillshare-6a544',
    authDomain: 'skillshare-6a544.firebaseapp.com',
    storageBucket: 'skillshare-6a544.firebasestorage.app',
    measurementId: 'G-GKTV4VNEJL',
  );
}
